plugins:
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - 'db/migrate/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15
